### ISSUE TITLE
App died after clicking ANOVA in Basic Statistics

### ISSUE THREAD

**Issue by lius24** [ModelingAndAnalysisOfUncertainty/ModelingAndAnalysisOfUncertainty#4]
For instance, you open file "EEA1.....FDA", and you successfully draw the graph using Artificial Neural Network. If you want to see other graphs, you can just choose other feature like Multivariate Statistics --> PCA --> PCM to see the graph directly without restarting the app. For the same file, this time we use ANOVA first, the app will jump to a blank page. Then we try to use Multivariate Statistics --> PCA --> PCM, you will be able to see the box:"Select # components", but nothing shows up. 

It seems only have conflict between Multivariate Statistics --> PCA --> PCM and ANOVA. Artificial Neural Network can work as usual after use ANOVA.

**Comment by hayTambourineMan** [comment]
Cannot figure out why, but can be solved with a clean reinstall.
